AWSTemplateFormatVersion: '2010-09-09'
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 3
Parameters:
  DeploymentPreference:
    AllowedValues:
    - Canary20Percent3Minutes
    - Canary50Percent1Minutes
    - Canary50Percent5Minutes
    - Canary10Percent5Minutes
    - Canary10Percent10Minutes
    - Canary10Percent15Minutes
    - Canary10Percent30Minutes
    - Linear10PercentEvery1Minute
    - Linear10PercentEvery2Minute
    - Linear10PercentEvery3Minute
    - Linear10PercentEvery10Minute
    - AllAtOnce
    Default: AllAtOnce
    Description: https://docs.aws.amazon.com/lambda/latest/dg/automating-updates-to-serverless-apps.html
    Type: String
  Env:
    AllowedValues:
    - prod
    - staging
    Default: prod
    Description: Define prod/staging by Parameters
    Type: String
Resources:
  HelloWorldFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://aftership-serverless-us-east-2-niko-bucket/c8af90416592e0149809cacf0571e92a
      DeploymentPreference:
        Alarms: null
        Type:
          Fn::Sub: ${DeploymentPreference}
      Events:
        HelloWorld:
          Properties:
            Method: get
            Path: /hello
            RestApiId:
              Ref: MyApi
          Type: Api
      FunctionName:
        Fn::Sub: sam-app-HelloWorldFunction-${Env}
      Handler: app.lambda_handler
      Runtime: python3.7
      Tracing: Active
    Type: AWS::Serverless::Function
  MyApi:
    Properties:
      StageName:
        Fn::Sub: ${Env}
    Type: AWS::Serverless::Api
Transform: AWS::Serverless-2016-10-31
